services:
  py3:
    build: .
    volumes:
      - type: bind
        source: "."
        target: "/workspace"
      - type: bind
        source: "/work00"
        target: "/work00"
      - type: bind
        source: "/home/kurita/.cache"
        target: "/root/.cache"
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0','1','2','3','4','5','6','7','8','9']
              capabilities: [gpu]